export const MAIN_SET_FETCHING = 'MAIN_SET_FETCHING'
export const MAIN_SET_MESSAGE = 'MAIN_SET_MESSAGE'

export const BATCHES_SET_DATA = 'BATCHES_SET_DATA'
export const PROJECTS_SET_DATA = 'PROJECTS_SET_DATA'
export const SAMPLES_SET_DATA = 'SAMPLES_SET_DATA'
export const TASKS_SET_DATA = 'TASKS_SET_DATA'

// experiments mutations types
export const SPLITS_SET_DATA = 'SPLITS_SET_DATA'
export const EXTRACTIONS_SET_DATA = 'EXTRACTIONS_SET_DATA'
export const DILUTIONS_SET_DATA = 'DILUTIONS_SET_DATA'
export const DISTRIBUTIONS_SET_DATA = 'DISTRIBUTIONS_SET_DATA'
export const ANALYSISES_SET_DATA = 'ANALYSISES_SET_DATA'
export const POOLINGS_SET_DATA = 'POOLINGS_SET_DATA'
export const LIBRARIES_SET_DATA = 'LIBRARIES_SET_DATA'
export const SEQUENCES_SET_DATA = 'SEQUENCES_SET_DATA'

// qcs
export const QCS_SET_DATA = 'QCS_SET_DATA'
export const QC_SET_DATA = 'QC_SET_DATA'

// result
export const RESULTS_SET_DATA = 'RESULTS_SET_DATA'
export const RESULT_SET_DATA = 'RESULT_SET_DATA'
